# Site settings
author: Sharonda Pettiett
title: Why did you decide to learn data science?
header-img: img/home-bg.png
email: spettiett@yahoo.com
copyright_name: Sharonda Pettiett
description: > # this means to ignore newlines until "baseurl:"
  Blogging Assignments for Flatiron Bootcamp
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  spettiett

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
